version: "3.9"

services:
  app:
    image: go-react
    build:
      context: .
      target: dev
    environment:
      APP_ENV: dev
      PORT: 8080
    volumes:
      - .:/app
    ports:
      - "18080:8080"
